### ISSUE TITLE
inconsistency bettween calls made via direct GET request and JSONP call

### ISSUE THREAD

**Issue by ls233** [nickloman/entrezajax#1]
I found an inconsistency bettween calls made via direct GET request and JSONP call.

direct GET: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=nucleotide&term=stat3[GENE]+AND+stat3[PROT]+AND+human[Organism]

result:<Count>1</Count>

the same but from JS:

args = {
            'apikey' : '2e2ba943f0a3f776806bc1ecd2387de3',
            'db' : 'nucleotide',
            //'term' : term+"[GENE]+AND+"+term+"[PROT]+AND+"+organism+"[Organism]"
            'term' : "db=nucleotide&term=stat3[GENE]+AND+stat3[PROT]+AND+human[Organism]"

```
    };

    console.log("args",args);

    $.getJSON('http://entrezajax.appspot.com/esearch?callback=?', args, function(data) {
        console.log("data",data);
```

/*

result:<Count>0</Count>

and the QueryTranslation looks somewhat off to me:
 "db=nucleotide[All Fields] AND term=stat3[GENE] AND +AND+stat3[PROT] AND +AND+human[Organism]"

Please advise
German

**Comment by nickloman** [comment]
Don't include 'db=nucleotide&' in the 'term' field .. this is taken from the 'db' parameter which you are already supplying.

Many thanks for your report.
